### ISSUE TITLE
初期起動時にコンパイルエラーが出る

### ISSUE THREAD

**Issue by MiraiHattori** [kyawawa/emacs.d#1]
抜粋です
Entering directory `/opt/ros/kinetic/share/emacs/site-lisp/'
^L
Compiling file /opt/ros/kinetic/share/emacs/site-lisp/rosemacs-config.el at Fri Apr 26 18:16:25 2019
rosemacs-config.el:33:1:Error: Cannot open load file: そのようなファイルやディレクトリはありません, yasnippet

**Comment by kyawawa** [comment]
~~yasnippetは必須ではないと思い、advancedの方にインストールの記述を書いていたのですが (https://github.com/kyawawa/emacs.d/blob/master/advanced/30-basics.el#L276 )、 ROSの設定でそれを使うための設定が書いてあるのが原因だと思います (https://github.com/kyawawa/emacs.d/blob/master/init/90-ros-mode.el#L53 )．
エラーにならない書き方をしているので問題はないのですが、emacs lispのコンパイルは変数とかマクロ周りが複雑で、なんでかエラーになってしまっていますね．．．
yasnnippetがadvancedであるという方針は変えなくて良いと思っているので、どうしたものか…~~

いや、rosemacs-config.elと書いてあるので僕のファイルのせいではないですね．
そして https://github.com/kyawawa/emacs.d/blob/master/init/90-ros-mode.el#L53 ここ誤字ってるのに気付きました．

**Comment by kyawawa** [comment]
分かりました．
エラーにある通り、ros-${ROS_DISTRO}-rosemacsで入るrosemacs-config.elにベタ書きで
```elisp
(require 'yasnippet)
```
とあるのですがそれがエラーになっていますね．
このファイルの記述をもっと良い感じにしたコードを自分で書いているので必要はないのですが、何も考えずにコンパイルしてしまっていました．
ということで、ベタ書き感は増しましたが 591b2df で修正されたと思います．
